"""
This script assumes that combined_data_china_winter2024.csv has been generated by combine_data.py.

This script implements feature engineering prior to model training. New features are calculated,
such as wind speed and relative humidity.

Seth Orvin
"""

import pandas as pd
import numpy as np
import os
from metpy.units import units # version 1.5.1
from metpy.calc import relative_humidity_from_dewpoint

# Get the path to the data directory, relative to this script
script_dir = os.path.dirname(os.path.abspath(__file__))
data_dir = os.path.join(script_dir, '..', 'data')
data_path = os.path.join(data_dir, 'combined_data_china_winter2024.csv')

# Load data into a DataFrame
df = pd.read_csv(data_path, parse_dates=['time'], low_memory=False)
df.sort_values(by=['station', 'time'], inplace=True)

# Calculate wind speed from u10 and v10
df['wind_speed'] = np.sqrt(df['u10']**2 + df['v10']**2)

# Convert temperature and dewpoint to kelvin for MetPy
temps = df['t2m'].values * units.kelvin
dewpoints = df['d2m'].values * units.kelvin

# Calculate relative humidity (RH)
rh = relative_humidity_from_dewpoint(temps, dewpoints)
df['relative_humidity'] = rh.magnitude

# Save combined data to CSV
processed_data_path = os.path.join(data_dir, 'processed_data_china_winter2024.csv')
df.to_csv(processed_data_path, index=False)
print("Combined data saved to:", processed_data_path)

print(df)
print(df.columns)